server:
  port: 8082
  servlet:
    context-path: /api/v1/roomBillz/notification  

spring:
  application:
    name: ROOMBILLZ-NOTIFICATION-SERVICE
#Database Configuration     
  datasource:
    url: jdbc:mysql://localhost:3306/roombillz_notification
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
 
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

#Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    
    consumer:
      group-id: roomBillz-notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

#Custom Kafka properties for topic and group mapping
kafka:
  topics:
    roomBillz: roomBillz-topic
    notification: roomBillz-notification-topic
  groups:
    roomBillz: roombillz-group
    notification: roomBillz-notification-group      
    
      
#Acatuator Configuration    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      